src/Google/Auth/ComputeEngine.php, tests/general/testdata/ComputeEngineAuthTest.php
=> Initial Compute Engine credentials for #457.

README.md, src/Google/Auth/AssertionCredentials.php, src/Google/Auth/ComputeEngine.php, src/Google/Auth/OAuth2.php, src/Google/Auth/Simple.php, src/Google/Client.php, src/Google/Config.php, src/Google/Http/Batch.php, src/Google/Http/CacheParser.php, src/Google/Http/MediaFileUpload.php, src/Google/Http/REST.php, src/Google/Model.php, src/Google/Service/Resource.php, src/Google/Utils.php, tests/pagespeed/PageSpeedTest.php
- Remove stale authors
- Add note on hd param security
- Add prettyPrint
- Fix bad autoloader incluson
=> Fix several issues

autoload.php
from #437 comments:
https://github.com/google/google-api-php-client/pull/437#discussion-diff-23418551
=> avoid searching include path

src/Google/IO/Curl.php
=> Fix typo in comment

.gitignore, examples/batch.php, examples/fileupload.php, examples/idtoken.php, examples/multi-api.php, examples/service-account.php, examples/simple-query.php, examples/simplefileupload.php, examples/templates/base.php, examples/user-example.php
=> Fix missing value errors to be more helpful in examples

src/Google/IO/Abstract.php
Fixes https://github.com/google/google-api-php-client/issues/529
=> Wrong documentation in Abstract.php

tests/general/IoTest.php
Fixes https://github.com/google/google-api-php-client/issues/525
=> Removed unused variables in IoTest.php

src/Google/Service/Resource.php
Fixes https://github.com/google/google-api-php-client/issues/531
=> Removed (duplicated) userip parameter

src/Google/Service.php, src/Google/Service/Resource.php, tests/general/ResourceTest.php
This adds support for per-service root url definitions.
=> Add support for per-service root url definitions

src/Google/Client.php
=> Bump version for dev master.

src/Google/Service/Pubsub.php
This is an attempt to fix #618 and #567 by upgrading the pubsub library to v1
=> updates pubsub from v1beta2 to v1

src/Google/Cache/File.php
Check commit message for details.
=> Stricter unix permissions for cache files.

src/Google/Service/Classroom.php, src/Google/Service/Compute.php, src/Google/Service/Directory.php, src/Google/Service/Doubleclicksearch.php, src/Google/Service/Games.php, src/Google/Service/GamesManagement.php, src/Google/Service/IdentityToolkit.php, src/Google/Service/Reseller.php, src/Google/Service/SQLAdmin.php, src/Google/Service/TagManager.php, src/Google/Service/YouTube.php
This change has been generated by a script that has detected changes in the
discovery doc of the API.
Check http://developers.google.com/discovery for more info.
=> Update v2 generated libs

src/Google/Service/Classroom.php, src/Google/Service/Compute.php, src/Google/Service/Directory.php, src/Google/Service/Doubleclicksearch.php, src/Google/Service/Games.php, src/Google/Service/GamesManagement.php, src/Google/Service/IdentityToolkit.php, src/Google/Service/Reseller.php, src/Google/Service/SQLAdmin.php, src/Google/Service/TagManager.php, src/Google/Service/YouTube.php
This change has been generated by a script that has detected changes in the
discovery doc of the API.
Check http://developers.google.com/discovery for more info.
=> Update v1 generated libs

src/Google/Service/Pubsub.php
There was an issue where `pubsub` was stuck on `v1beta1` instead of `v1`
Check http://developers.google.com/discovery for more info.
=> Updated Pubsub to v1

src/Google/Client.php, tests/Google/ClientTest.php
=> fix fetchAccessTokenWithAssertionCredentials

src/Google/Http/REST.php, src/Google/Service/Resource.php, tests/Google/Service/ResourceTest.php
Adds tests and exception handling for #728
=> Additional Support for alt=media

src/Google/Http/Batch.php, tests/Google/Http/BatchTest.php
=> fixes batch requests for POST

README.md
=> add banner to README to clarify version docs discrepancy

src/Google/Service/Resource.php, tests/Google/Http/BatchTest.php
=> fixes batch uploads with PSR7

src/Google/Cache/File.php, tests/Google/CacheTest.php
=> File cache umask

src/Google/Cache/File.php, tests/Google/CacheTest.php
Addresses permission concerns with filecache (@tmatsuo PTAL)
=> use hashed username in cache dir

src/Google/Cache/File.php
=> use correct get process user function

examples/multi-api.php
```
$service = new Google_Service_Drive($client);
```
This line is not seems to be necessary here.
=> removed unused line

examples/idtoken.php
=> id_token_token instead of id_token

examples/multi-api.php
=> multi-api-token instead of access_token

src/Google/Http/Batch.php
…although it doesn't seem to matter
=> header lines get messed up without this

src/Google/Client.php
=> passes in cache to token verifier by default

src/Google/Service/README.md
=> Create README.md in src/Google/Services 

src/Google/Service/AnalyticsReporting.php
I would like to add the **Analytics Reporting API V4** service to the **Google APIs Client Library for PHP** `v1-master` branch, to make it easy for our current php developers to take advantage of the new API without migrated their code to the master branch.
=> Added Analytics Reporting API V4 to v1-master branch.

src/Google/AccessToken/Revoke.php, tests/Google/AccessToken/RevokeTest.php
=> allows string tokens in revoke method

src/Google/Client.php
=> Remove references to Google_Config

src/Google/Client.php
Correct DocBlock @throws to LogicException
=> Correct DocBlock @throws to LogicException on Client.php

src/Google/AuthHandler/Guzzle5AuthHandler.php, src/Google/AuthHandler/Guzzle6AuthHandler.php
=> fixes issue with BC breaking google/auth change

src/Google/Client.php, tests/Google/ClientTest.php
=> uses syslog handler on appengine

composer.json
[google/apiclient-services: v0.8](https://github.com/google/google-api-php-client-services/tree/v0.8)
[google/auth:v0.11](https://github.com/google/google-auth-library-php/tree/v0.11.0)
[firebase/jwt:v4.0](https://github.com/google/google-api-php-client/pull/1063)
=> updates composer dependencies

src/Google/Client.php, tests/BaseTest.php
Fix unused params in a test class
=> Fix unused params

.travis.yml, composer.json, oauth-credentials.json, service-account-credentials.json, src/Google/AccessToken/Verify.php, tests/Google/AccessToken/VerifyTest.php
=> allows for older versions of phpseclib

src/Google/Client.php
=> update libver version

src/Google/Client.php, tests/Google/ClientTest.php
=> ensures refresh token is added back to the access token, adds tests

src/Google/AccessToken/Revoke.php, src/Google/AccessToken/Verify.php, src/Google/Client.php, src/Google/Collection.php, src/Google/Http/Batch.php, src/Google/Http/MediaFileUpload.php, src/Google/Http/REST.php, src/Google/Model.php, src/Google/Service/Resource.php, src/Google/Task/Runner.php, tests/BaseTest.php, tests/Google/ClientTest.php, tests/Google/Service/TasksTest.php, tests/Google/ServiceTest.php
I recently run into the "only Php talk" video and thought that supporting our community member would be a good idea =)
Tweaks found and fixed automatically by [Php Inspections (EA Extended)](https://github.com/kalessil/phpinspectionsea) (my pet-project):
- dead code;
- control flow simplifications;
- language level and code style;
=> [Minor] Static Code Analysis with Php Inspections (EA Extended)

src/Google/Client.php
Logger is an implementation of `Psr\Log\LoggerInterface`.
=> Fixed logger property docblock.

tests/Google/AccessToken/VerifyTest.php, tests/Google/ClientTest.php, tests/Google/ModelTest.php, tests/Google/ServiceTest.php, tests/examples/batchTest.php, tests/examples/idTokenTest.php, tests/examples/indexTest.php, tests/examples/largeFileDownloadTest.php, tests/examples/largeFileUploadTest.php, tests/examples/multiApiTest.php, tests/examples/simpleFileUploadTest.php, tests/examples/simpleQueryTest.php, tests/examples/urlShortenerTest.php
I've refactored some tests with [`assertCount`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertCount), [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse), [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue) and [`assertNull`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertNull) methods.
=> Refactoring tests

src/Google/AccessToken/Verify.php
=> Ensures leeway is at least 1, instead of setting it to 1

README.md
=> Update readme.md, remove Stash, add Cache

src/Google/Client.php, tests/BaseTest.php, tests/Google/ClientTest.php
Addresses: https://github.com/google/google-auth-library-php/issues/205
=> Use new auth urls

src/Google/Client.php, tests/Google/ClientTest.php
=> Update default and doc values for setApprovalPrompt.

src/Google/Client.php
as Google_AccessToken_Revoke::revokeToken() accepts it
=> revokeToken() accepts arrray too

src/Google/Http/Batch.php
Replaces #1554 with documentation changes.
=> Add batch reset warning

src/Google/Client.php
* Fixing the ability to provide custom retryMap (#1488)
* Use new auth urls (#1492)
* Use double pipes in composer dependency file (#1505)
* Fix usage of undefined constants (#1621)
* Specify configuration filepath when config file is not found (#1626)
* Add UnexpectedValueException to documentation (#1592)
* Add batch reset warning (#1613)
* Remove extra setAccessKey call in examples. (#1469)
* Updates phpdoc for Google_Client::setScopes (#1465)
* Small changes to examples/index.php (#1460)
* misc updates to examples/url-shortener.php (#1456)
* Update docs to install latest 2.x version (#1491)
* Fix build status image (#1549)
* fix tests (#1560)
* Update `Google_Client::revokeToken()` docblock. (#1609)
* Add guzzle config to readme (#1625)
=> Prepare for v2.2.3

README.md, docs/oauth-server.md
Fixes: https://github.com/googleapis/google-api-php-client/issues/1669
=> docs: Update links in README to point to new docs living inside repo

src/Google/Client.php
=> docs: Add note about cached access token

README.md
=> docs: Change composer alternative wording.

src/Google/Client.php
* Add option to toggle API format version. (#1644)
* Fix order of arguments for implode in Google_Service_Resource. (#1688 
* Run tests against PHP 7.3+ and check for cross-version support. (#1684)
* Delete url-shortener.php (#1646)
* Adds developer docs to repo. (#1668, #1670)
* Fix docs link (#1673) 
* Update README links (#1677)
* Remove note about PHP 5.2 support (#1678)
* Add note about cached access token (#1696)
* Update api-keys.md (#1699)
* Change composer alternative wording. (#1697)
=> Prepare v2.2.4

README.md
please file a issue > please file an issue
=> Fix indefinite article in README.md

composer.json, tests/Google/Service/ResourceTest.php
=> feat: Support Monolog v2

src/Google/Client.php
* Add x-goog-api-client header to requests. (#1709)
=> Prepare v2.4.0

.travis.yml
This has been deprecated by travis and doesnt do anything anymore
=> chore: remove sudo:false

docs/install.md
=> chore: fix documentation typo

docs/oauth-server.md
=> docs: remove duplicate lines from oauth-server.md

docs/oauth-web.md
fixes https://github.com/googleapis/google-api-php-client/issues/1795
=> docs: change setApprovalPrompt to setPrompt

README.md
Related to: https://github.com/googleapis/google-api-php-client-services/issues/169#issuecomment-582101676
=> docs: use explicit getter in sample over iterator interface methods

docs/oauth-web.md
Hi! One thing left unchanged after #1796
=> Documentation fix: change setApprovalPrompt to setPrompt

UPGRADING.md
=> docs: fix upgrade guide cache note

README.md, composer.json, src/Google/Client.php, tests/Google/ClientTest.php
Depends on https://github.com/googleapis/google-auth-library-php/pull/277 for the `quota_project` option to work
=> feat: adds new client options

src/AccessToken/Revoke.php, src/AccessToken/Verify.php, src/Client.php, src/Http/Batch.php, src/Http/MediaFileUpload.php, src/Http/REST.php, src/Model.php, src/Service.php, src/Service/Exception.php, src/Service/Resource.php, src/Task/Composer.php, src/Task/Runner.php, src/aliases.php
=> chore: fix docblock namespaced references

.github/workflows/asset-release.yml
=> ci: fix github actions asset release for composer 2

phpcs.xml.dist, src/aliases.php
Adds fix for errors from IDE static analysis tools
Fixes https://github.com/googleapis/google-api-php-client/pull/1984
Fixes https://github.com/googleapis/google-api-php-client/issues/1994
=> fix: add classes in aliases.php for IDEs

src/Client.php
* add classes in `aliases.php` to fix IDE error (#1995)
=> chore: prepare v2.8.3

src/Client.php
* fix asset release and documentation generation (#2030)
=> chore: prepare v2.9.1

src/aliases.php
=> fix: IDE alias for Google_Task_Retryable is an interface

README.md
=> chore(docs): update README for google/cloud libraries, and add Compute

README.md, src/Client.php
Depends on #2131 
- allow guzzlehttp/psr7 v2  (#2128)
- add 8.1 compatibility and tests (#2113)
=> chore: prepare v2.11

README.md, src/Client.php
- allow credentials object (#2153)
=> chore: prepare v2.12

src/Collection.php, src/Model.php
Addresses https://github.com/googleapis/google-api-php-client/issues/2178
=> chore: add explicit return types to address Symfony deprecations

.github/workflows/tests.yml
=> chore: clean up workflows

composer.json
=> update to patched version of psr7

src/AccessToken/Verify.php
fix #2244 and #2243
We already have tests to cover this, but they were being skipped in CI because they require specific auth credentials
=> fix: bad firebase call

src/Client.php
https://github.com/googleapis/google-api-php-client/issues/2247
=> Fix unknown class ResponseInterface in docblock during Psalm analysis

src/Client.php, src/Http/MediaFileUpload.php, src/Http/REST.php
=> fix: MediaFileUpload fatal error

src/Client.php, tests/Google/ClientTest.php
=> fix: ensure new redirect_uri propogates to OAuth2 class

src/Service/Resource.php, tests/Google/Service/ResourceTest.php
=> Send no content-type header if there is no body

README.md
Added a note about composer timeouts in the readme.
=> docs: Update readme to add timeout fix for composer

composer.json
=> fix: disallow vulnerable guzzle versions

composer.json
=> Fix guzzle dependency version

composer.json
=> chore: Increase minimum supported version for guzzlehttp/psr7

composer.json
=> chore: Support minimum composer/composer v1.10.23
