src/Google/Cache/File.php
Removed the assumption of successful file handle acquisition while trying obtain a lock on a cache file. This has caused the following errors to pop up in my logs:
`flock() expects parameter 1 to be resource, boolean given`
In other words we shouldn't try and get a lock on a file we can't open. I suppose the eventual solution would be to find why the file can't be opened in the first place, but, this only happens occasionally so it might be some kind of race condition or something.
=> flock() not getting file handle all the time

src/Google/Http/REST.php, src/Google/Http/Request.php, src/Google/Service/Resource.php
Currently when running a get request on storage with `alt=media` the library will try and decode the response into json, however when `alt=media` is specified to download the file the api returns the file contents as the body. In this case the library should simply return the raw body without trying to decode. #480
=> Fix for file download from cloud storage

src/Google/IO/Curl.php
Will allow developers to set additional cURL options when needed.
For example, googleapis.com resolves to both IPv4 and IPv6 addresses now. Some hosting providers don't have IPv6 support and a cURL request will fail when trying to connect to an IPv6 address.
Being able to set cURL options, developers can handle this issue using CURLOPT_IPRESOLVE to force IPv4, IPv6 or Both.
=> Allow cURL options to be set through setClassConfig

src/Google/Collection.php
I tried to check for Shopping Content accounts if there are products uploaded for specific accounts:
```php
$service = new Google_Service_ShoppingContent($Client);
$productList = $service->products->listProducts($account['id']);
print_r($productList->count());
```
If the account does not have any products yet, I'd expect the count to be 0, however a warning gets triggered:
> PHP Notice:  Undefined index: resources in .../vendor/google/apiclient/src/Google/Collection.php on line 51
=> no notice for count on empty collections

src/Google/Auth/AppIdentity.php, src/Google/Auth/Simple.php
Fixes https://github.com/google/google-api-php-client/issues/527
=> Unused private variables in Authentification classes

src/Google/Service/Resource.php
In order to avoid problems with recursion, I would suggest to store in the resource object only the information necessary from the service, in this case path.
Fixes https://github.com/google/google-api-php-client/issues/533
=> Removed service to avoid recursion problem

src/Google/Http/REST.php
According to documentation, for filters, URL-reserved characters — Characters such as & must be url-encoded in the usual way, see https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filterExpressions
If in a filter such as ga:pagePath an URI is used, which needs to be url-encoded, the createRequestUri method will apply an additional rawurlencode() on it resulting in a double URL encoding.
=> Avoid double URL encoding for params' values

examples/fileupload.php
While the sample code works file from a local file.  If you're reading from a URL, it's very inefficient.  The sample code here is reading from a URL and is very inefficient.
https://developers.google.com/youtube/v3/code_samples/php#resumable_uploads
It looks like it was pulled directly from the sample code in GitHub
=> More efficient file upload from URL

src/Google/Auth/OAuth2.php, src/Google/Client.php
Here's a pull request to allow for valid authenticate requests, using an authorization code obtained through the cross client authorization scheme, as described here https://developers.google.com/identity/protocols/CrossClientAuth
As the documentation sais, the request body should not include the request_uri argument.
=> Allow for valid cross client authentication requests

src/Google/Http/Batch.php, src/Google/Service.php, tests/general/Http/BatchTest.php, tests/general/ServiceTest.php
Presently, batch URLs use the system configured global URL and a hard-coded batch path. This PR allows for services to specify the batch end point. 
It also fixes a problem with batches not correctly terminating headers when there is no body to the request.
=> Add separate createBatch method to propagate batch URLs properly

.travis.yml
=> Fix: Install dependencies in install section on Travis

.travis.yml, README.md, composer.json, src/Google/Auth/OAuth2.php, src/Google/Client.php, src/Google/Collection.php, src/Google/Config.php, src/Google/Http/MediaFileUpload.php, src/Google/Http/Request.php, src/Google/Model.php, src/Google/Service.php, src/Google/Service/Cloudsearch.php, src/Google/Service/Genomics.php, src/Google/Service/Playmoviespartner.php, src/Google/Signer/P12.php, src/Google/Utils/URITemplate.php, src/Google/autoload.php
=> Enhancement: Run phpcs on Travis

.travis.yml
=> Fix: Update Composer itself in before_install section

.gitignore, tests/BaseTest.php, tests/OAuthHelper.php
When an access token isn't set, the PHPunit skip message directs the user to run the oauth helper:
```bash
$ phpunit -v
27) AdSenseManagementTest::testReportsGenerate
Test requires access token
run "php tests/OAuthHelper.php"
```
The access token is stored in `tests/.accessToken` and ignored by git, so your testing does not leave modified files in your workspace.
```bash
$ php tests/OAuthHelper.php
Please enter the auth code:
4/FA7m3UKJIeBLLmf8vpnJzCTLGXYR7a521_IF-Bo_xVw
successfully loaded access token
```
When this is run, it now asks you to set `GCLOUD_CLIENT_ID` and `GCLOUD_CLIENT_SECRET` as environment variables, if these are not already set.
```
$ php tests/OAuthHelper.php
fetching a token requires GCLOUD_CLIENT_ID and GCLOUD_CLIENT_SECRET to be set
```
=> easier access token testing

src/Google/Http/MediaFileUpload.php
I'm receiving chunked data with different size from some service and I would like to upload max available part of those chunks (multiple 262144 b),  but I can't set the `chunkSize` for every step of resumable upload.
=> Google_Http_MediaFileUpload::chunkSize make settable

src/Google/Http/MediaFileUpload.php
This Pull Request adds Support to resume an upload to google Drive, as asked in #658.
To achieve this, the following changes were Made:
* Renamed the `getResumeUri()`-Method to `fetchResumeUri()`, as it's more clear
* Added the Method `getResumeUri()` which is now used as a getter for the private `resumeUri`-property. 
* Added a `resume($uri)`-method to be called with an resumeUri, which will fetch the upload status & setup the object (set the resumeUri & progress properties).
* Moved code from `nextChunk()` to the new private `makePutRequest($request)` method to avoid duplicating code from `nextChunk()` in `resume()`.
With this changes, any chunked upload can be easily paused (or a better error-handling can be implemented) by simply getting the resumeURI from the …
=> Add methods to resume Uploads

src/Google/Http/REST.php, tests/Google/Http/RESTTest.php
Move JSON parsing to inside error handling and after alt=media check to prevent attempts to parse non-json content.
=> Fix #709 - Don't attempt JSON parsing if alt=media requested

src/Google/Service/Resource.php
Switches the order of the array merge to not occlude parameters defined in the API. Note that this isn't a long term fix. In the particular case I found this, it was the mimeType parameter that conflicted. The method in question didn't involve media upload, so no conflict.
But it possible that at some point an API will come along where we'll need to disambiguate better.
=> Prefer parameter definitions from API

src/Google/Client.php, tests/Google/ClientTest.php
This is required for AppEngine calls to a succeed, otherwise the connection error `Curl Errno 7` is thrown.
We could only do this for when `isAppEngine` is true, but I'm a fan of as few conditional checks as possible. Are there any downsides to defaulting to this StreamHandler over Curl?
=> uses guzzle StreamHandler by default [AppEngine only]

README.md, src/Google/autoload.php
This is to address [user concerns](http://stackoverflow.com/questions/33483326/how-do-i-use-composer-to-setup-google-api-php-client) regarding composer support. 
In addition, we will be adding a downloadable zip file to each project that includes all the dependencies, for those users who would prefer to not use composer.
=> adds composer support in README and adds autoload back

src/Google/autoload.php
To keep minimum requirements at PHP 5.2.1 or higher, anonymous functions shouldn't be used in autoload.php. Anonymous functions are not available prior to PHP 5.3.
=> PHP 5.2.x compatibility issue

src/Google/Http/REST.php
When calls cause an exception the error response is passed to `decodeHttpResponse` method directly. When using Guzzle 5, that response is not a PSR-7 response, which causes an error.
This pull requests catches that and converts it if necessary.
=> Handle exceptions correctly when using Guzzle 5

src/Google/Config.php, src/Google/IO/Curl.php
As discussed in #190, this PR adds a configuration option that is designed to be set by users with old cURL versions but where the vendor has backported a fix for the specific bug that was being worked around (again, see #190 for more detail). In that case, we need to allow users the option of disabling our workaround, since there is no reliable way to detect the presence of the fix at runtime.
=> Make cURL proxy header calculation bug workaround configurable

src/Google/Http/REST.php, tests/Google/Service/ResourceTest.php
=> cleans up REST::decodeResponse

composer.json
Classmaps are the anti-autoloader pattern. With the number of classes this pulls in, this is memory-intensive (every class-lookup pulls in the classmap).
We have a wonderful custom autoloader in `v1` that we should just tell composer to use. This will make everyone happy.
=> uses custom autoloader instead of classmap - much better

composer.json
In preparation to BC changes about to be merged in https://github.com/google/google-api-php-client-services/pull/25, we will update this version of the library to depend on `google/apiclient-services:v0.5`
=> tag client services

src/Google/Client.php
Fixed "setApprovalPrompt" method documentation to the code right default.
Here you can see the default value to approval_prompt is "auto": [Client.php#L129](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L129)
=> Fix the approval_prompt default value documentation.

src/Google/Client.php
Fixed unused parameters '$authHttp' in the class Client, method authorize()
=> Fixed unused parameters

.gitattributes
Don't distribute tests, build files etc. when installing with Composer with `--prefer-dist` (the default). This saves lots of bandwith and file extraction when installing dependencies with default settings.
=> Don't distribute tests, build files etc. for composer

src/Google/Http/Request.php, tests/general/RequestTest.php
Solves https://github.com/google/google-api-php-client/issues/1046 for the legacy version
=> Update the Google HTTP Request class to use the `arg_seperator` in the http_build_query call

src/Google/Collection.php, src/Google/Model.php, tests/Google/ModelTest.php
Makes the following array-passing in the constructor and manual class creation identical:
*\* BEFORE **
``` php
$query = new \Google_Service_Datastore_Query();
$order = new \Google_Service_Datastore_PropertyOrder(['direction' => 'descending']);
$property = new \Google_Service_Datastore_PropertyReference(['name' => 'created']);
$order->setProperty($property);
$kind = new \Google_Service_Datastore_KindExpression(['name' => self::KIND]);
$query->setOrder([$order]);
$query->setKinds([$kind]);
$query->setLimit($limit);
```
*\* AFTER **
``` php
$query = new \Google_Service_Datastore_Query([
'order' => [
[
'direction' => 'descending',
'property'  => [ 'name' => 'created' ],
],
],
'kinds' => [
[ 'name' => self::KIND ],
],
'limit' => $limit,
]);
```
=> Improve model contructor api

src/Google/Service/Resource.php
Okay, in Resources.php, it's possible for `$paramSpec['repeated']` to not be set while `$paramSpec['value']` is an array. This causes execution to fall through to line 280 and then throw a warning on `rawurldecode($paramSpec['value'])`, which expects a string, and then the request to the API will fail.
Checking if `$paramSpec['value']` is an array and then setting it to the first element if so solves the problem.
Not sure if this is the best solution, it's just the one I'm using right now to get the thing working at all.
=> Added missing is_array check

src/Google/AccessToken/Verify.php
As stated by @vocoded on the issue #1279 firebase/php-jwt changed the way they report a problem with the certificate. If the signature is invalid, the verify function won't throw a `DomainException` and instead it will return `false` and then the decode function will throw a `SignatureInvalidException`. This fix adds the later exception to the catch chain so it will continue trying with other certificates.
I wasn't able to replicate the issue with a test but I try this fix on my project and it seems to had the problem fixed.
tl;dr
This fixes #1279
=> Add missing exception to the catch chain

src/Google/Collection.php, src/Google/Model.php, tests/Google/ModelTest.php
Any object extending `Google_Model` looks for the property name appended with `Type` to decide if that property is a complex type. If `$property + 'Type'` exists, the library tries to instantiate a class of `$property + 'type'`.
In the case of DfaReporting, both `$duration` and `$durationType` are valid properties, and `$duration` is not a complex type. This change ensures that the classes exist before trying to create them, thus getting around the typing conflict.
=> addresse keytype conflict

composer.json, tests/BaseTest.php, tests/Google/ServiceTest.php
Simplify version of #1334.
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
Just needed to bump PHPUnit version to [`4.8.36`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4836---2017-06-21), to keep compatibility.
=> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

src/Google/AccessToken/Verify.php
Looking at http://www.php-fig.org/psr/psr-6/ it seems `getItem` accepts only one parameter. The expiration must be set on the `CacheItemInterface` instance
=> fix certificate caching, fixes #1033

tests/Google/AccessToken/VerifyTest.php, tests/Google/Http/BatchTest.php, tests/Google/Http/MediaFileUploadTest.php, tests/Google/Service/PlusTest.php, tests/Google/Service/TasksTest.php, tests/examples/serviceAccountTest.php, tests/examples/simpleQueryTest.php
Continuing to refactory tests, like #1352, I've used:
- `assertArrayHasKey` instead of `isset` function;
- `assertGreaterThan` for mathematical comparisions;
- `assertCount` instead of `count` function;
- `assertInternalType` avoiding using `is_*` functions.
=> Refactoring tests

src/Google/Service/Resource.php, tests/Google/Service/ResourceTest.php
Report stop channel and Directory stop channel methods uses a different service path then their default class. When the lib build the full service url, the service path is duplicated.
=> Fix directory and reports stop channel urls 

examples/idtoken.php
=> examples: Remove extra setAccessKey call.

src/Google/Client.php
Using a string is valid as the addscope() function accepts it as well.
This usage is present in the `clientTest.php` file and also in the
example from the quickstart, but currently gives out a warning on static
analysis of code, as it isn't seen as a valid input.
Resolves #1464
=> Updates footprint cq phpdoc to include string for $scopes

src/Google/Client.php
https://github.com/google/google-api-php-client/issues/1487
=> Fixing the ability to provide custom retryMap

tests/Google/ClientTest.php
A patch in the `guzzlehttp/psr7` package now causes exceptions to be thrown when a `GuzzleHttp\Psr7\Response` object is instantiated without a valid status code.
=> Fix tests - expect getStatusCode to return a 200 code

src/Google/Client.php, tests/Google/ClientTest.php
Prompt is not the same thing as approval prompt. Their parameters do get mistaken for each other on some doc pages though.
=> Revert #1535.

src/Google/Client.php
=> Add UnexpectedValueException to documentation

src/Google/Client.php
=> Specify configuration filepath  when config file is not found

README.md
A common question relates to modifying the HTTP client options. This change calls out the answer more clearly in the README (it was there before, but under a heading that one wouldn't look for).
Closes #1600.
=> Add guzzle config to readme

README.md
This change removes the part of the README explaining why we still support PHP 5.2, since... we don't, and haven't since [2015](https://github.com/googleapis/google-api-php-client/commit/48dfd9571854d35b2fda1db15b918e6976d7d1e6). 😆
=> Remove note about PHP 5.2 support

src/Google/Service/Resource.php
For historical reasons `implode()` accepts its parameters in either order. However, PHP 7.4 now deprecates this. The glue should always be the first argument.
Note: this might be a good time to start testing against PHP 7.3 on Travis, as well as against 7.4, but with allowed failures.
=> Fix order of arguments for implode in Google_Service_Resource

.travis.yml, composer.json, tests/BaseTest.php, tests/Google/AccessToken/RevokeTest.php, tests/Google/AccessToken/VerifyTest.php, tests/Google/ClientTest.php, tests/Google/Service/ResourceTest.php, tests/Google/ServiceTest.php, tests/Google/Task/RunnerTest.php
In older versions of PHPUnit, the mocking framework has fairly major compatibility issues with PHP 7.4, and due to (in my opinion) questionable decisions taken by the maintainers to not backport fixes to anyone using less than PHP 7.2, will not be taking action to address this in a way we can make use of.
This change replaces the PHPUnit mocks with prophecy mocks. ~~Once [this PR](https://github.com/phpspec/prophecy/pull/432) is tagged by prophecy, we will be able to remove the allow failures tag from PHP 7.4.~~ done.
=> tests: Upgrade unit tests for PHP 7.4 compat

src/Google/Client.php
* fix documentation typo (#1741)
* remove shutdown G+ API references (#1751)
* remove duplicate lines from oauth-server.md (#1761)
* update README (#1779)
* change setApprovalPrompt to setPrompt (#1796)
* use explicit getter in sample over iterator interface methods (#1783)
* upgrade unit tests for PHP 7.4 compatibility (#1710)
* remove sudo:false from travis config (#1732)
=> Prepare v2.4.1

README.md
This change adds a warning to users to pin to a specific version of `google/apiclient-services` and also a guide to how they can skip installation of services if they don't need them.
=> docs: update readme with info on services repo

README.md
Follow-up to https://github.com/googleapis/google-api-php-client/pull/1823#issuecomment-626663419
=> docs: add link to google/apiclient-services release page

.gitattributes
This commit is part of a campaign to reduce the amount of data transferred to save global bandwidth and reduce the amount of CO2. See https://github.com/Codeception/Codeception/pull/5527 for more info.
I don't see any reason why the docs folder should be part of the zip archive. If this is needed for other cases, please let me know.
=> chore: update ignored files for exporting package

.github/workflows/asset-release.yml
This adds a Github action to automatically generate and upload release assets when a new release is created.
This has a couple advantages over the manual process:
- It runs natively on multiple versions of PHP, so we don't need `--prefer-lowest`.
- We can generate releases for more versions of PHP. I'm running it here for 5.4, 5.6, 7.0 and 7.4.
- **It's automatic**
[Sample Run](https://github.com/jdpedrie/google-api-php-client/runs/784602695)
[Sample Release](https://github.com/jdpedrie/google-api-php-client/releases/tag/v2.4.15)
=> chore: automate asset release

.travis.yml, composer.json, src/Google/AuthHandler/AuthHandlerFactory.php, src/Google/AuthHandler/Guzzle6AuthHandler.php, src/Google/AuthHandler/Guzzle7AuthHandler.php, src/Google/Client.php, tests/BaseTest.php, tests/Google/ClientTest.php
Same as #1860 but updated for `google/auth:1.10.0` and a few other fixes.
=> feat: Guzzle 7 support

.gitattributes
During my previous PR https://github.com/googleapis/google-api-php-client/pull/1848 this line has been overlooked.
=> Add missing export-ignore

src/Google/Http/REST.php, src/Google/Utils.php
Remove depreciation warnings for php 7.4 which cause some unit tests to fail
=> chore: fix deprecated syntax

tests/Google/Http/BatchTest.php
Followup to #1687 and test failures.
=> test: fix batch tests

src/Google/Http/MediaFileUpload.php
Pull request https://github.com/googleapis/google-api-php-client/pull/1872 adds some parameter type hints to code
For parameter `$chunk` in  `MediaFileUpload::nextChunk` it specifies a `bool` type but `string` should be also accepted because the implementation treats this parameter as it a string is.
=> docs: fix invalid parameter type-hint for nextChunk

examples/batch.php
This is because the Books API does not work with `createBatch`, and only works when using the shared batch endpoint.
=> chore: add comment for batching

src/Google/Client.php, tests/Google/ClientTest.php, tests/Google/Task/ComposerTest.php
=> fix: ensures in-memory access token is updated when refresh token is used

src/Google/Client.php
- ensure in-memory access token is updated when refresh token is used (#1926)
- use quota_project_id over quota_project (#1914)
=> chore: prepare v2.7.1

src/Google/AuthHandler/Guzzle6AuthHandler.php, src/Google/Client.php, tests/Google/ClientTest.php
Fix for #1964 
- default options `exceptions` changed to `http_errors` when guzzle version is 6 or 7. (The deprecation of `exceptions` was implemented in guzzle 6 and enforced in guzzle 7).
=> Issue 1965 - Exceptions option fallback to http_errors on guzzle 6 or 7

src/AuthHandler/Guzzle5AuthHandler.php, src/AuthHandler/Guzzle6AuthHandler.php, src/Client.php, tests/Google/ClientTest.php
- Passes cache to calls to `ApplicationDefaultCredentials::getCredentials` to take advantage of new onGce cache
- Wraps credentials in `FetchAuthTokenCache` on calls to `ApplicationDefaultCredentials::fetchAccessTokenWithAssertion`
=> feat: add caching for GCE and access tokens by default

.github/workflows/tests.yml, composer.json, tests/Google/Task/ComposerTest.php
Composer 2 came out, and our github actions upgraded to it. As a result we have some failing checks! Let's fix em...
=> Fixes for composer2

src/aliases.php
Fixes #1976 by not declaring aliases when classes already exist
=> fix: preload errror with aliases.php

src/Client.php
* fix preload error caused by `alias.php` (#1978)
* fix docblock references caused by new namespaces (#1977, #1980)
=> chore: prepare v2.8.1

src/aliases.php
Do not use autoload functionality when check class existence.
With default "true" it will fail on custom autoload.
=> Do not use autoload when check class existence.

.github/workflows/tests.yml
There was an extra space (easy to miss) which was making the names different in the sync repo settings file
=> fix: ensure names match sync repo settings

composer.json, src/AccessToken/Verify.php, tests/Google/AccessToken/VerifyTest.php
- Allow to install `phpseclib/phpseclib` with no composer conflicts.
- Adapt `Verify` class to new phpseclib classes and methods.
=> feat: support phpseclib3

src/Task/Runner.php
When retries are enabled in the client, the Runner class [by default](https://github.com/googleapis/google-api-php-client/blob/81696e6206322e38c643cfcc96c4494ccfef8a32/src/Task/Runner.php#L76) retries requests when the API returns a `500` error code. Unfortunately, the PageSpeed Insights [API](https://developers.google.com/speed/pagespeed/insights/) returns 5XX's for errors that should really be 4XX (specifically in Lighthouse for the errors ERRORED_DOCUMENT_REQUEST, FAILED_DOCUMENT_REQUEST). So 500 errors from this API shouldn't be retried, they will only increase load and fail again. 
These errors are non-retryable user defined errors: for example requesting data for a url that doesn't go anywhere. This PR changes the default client behavior to avoid retrying requests the the reason …
=> fix: exclude PageSpeed Insights API errors from retries.

src/Client.php
:heavy_exclamation_mark: Note that PHP versions 5.4 and 5.5 and phpseclib lower than version 2.0 are no longer supported.
* support phpseclib version 3 (#2019)
* add support for php 8 (#2017)
* ensure names match sync repo settings (#2022)
* exclude PageSpeed Insights API errors from retries. (#2010)
---
I'm assuming we'll merge #2010 before releasing this. @bshaffer can you confirm?
=> chore: prepare v2.9.0

src/Task/Composer.php
See https://github.com/googleapis/google-api-php-client-services/pull/363
=> fix: ensure composer cleanup works for upcoming service namespaces

README.md, tests/Google/Task/ComposerTest.php
Otherwise, composer's `optimize-autoloader` will dump ALL the files in `autoload_classmap.php`, even the ones removed by this task.
This PR also cleans up the `Google\Task\Composer` tests to make them cleaner and more readable.
=> chore: recommend 'pre-autoload-dump' for cleanup command so it works with 'optimize-autoloader'

composer.json
Fixes #2092
[From the Composer documentation](https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators):
> The ^ operator behaves very similarly, but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example ^1.2.3 is equivalent to >=1.2.3 <2.0.0 as none of the releases until 2.0 should break backwards compatibility. For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.
The important part being the last sentence.
=> Change google/apiclient-services requirement from ^0.200.0 to ~0.200

src/Client.php, tests/Google/ClientTest.php
Allows for a `Google\Auth\CredentialsLoader` instance to be passed into the constructor of `Google\Client` using the `credentials` option, which currently exists but only supports an array or string.
```php
$client = new Google\Client([
'credentials' => new AnonymousCredentials()
]);
```
This also solves #2142, which provides a way to enable self-signed JWT, but in a more general (and useful) way. 
```php
$scope = 'https://www.googleapis.com/auth/cloud-platform';
$jsonKey = json_decode(file_get_contents('./path/to/key.json'), true);
$credentials = Google\Auth\ApplicationDefaultCredentials::makeCredentials([
'scope' => $scope,
'jsonKey' => $jsonKey,
]);
// Enable self-signed JWT
$credentials->useJwtAccessWithScope();
$service = new Google\Service\BigQuery([
'credentials' => $credentials …
```
=> feat: allow credentials object

src/Http/Batch.php
The new version of PRS7 2.2.1 header validation is stricter this commit solves the header validation problem.
Current:
```
Vary: Origin\n
X-Origin\n
Referer\n
```
Should be:
```
Vary: Origin, X-Origin, Referer
```
https://github.com/guzzle/psr7
More information about concatenation of headers:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary
See https://github.com/googleapis/google-api-php-client/issues/2230
=> Fixed wrong header concatenation

src/Client.php, tests/Google/ClientTest.php
Related https://github.com/googleapis/google-api-php-client/issues/2217
=> Check token has expires_in attribute

src/AccessToken/Verify.php
Fixes https://github.com/googleapis/google-api-php-client/issues/2237
Additionally removed unused imports
=> Verify.php import InvalidArgumentException

.github/actions/docs/entrypoint.sh, .github/workflows/docs.yml
For some reason, when `generate documentation` is triggered on a tagged release, the `main` branch isn't generated. I could not reproduce this locally, and looking at the code, I cannot find out what is causing this behavior. So rather than have our documentation be broken after every release, we'll just remove the tag trigger. This will mean the `main` docs will be up-to-date, but the tags will lag behind. It's not ideal, but it's better than having our default documentation be broken.
=> chore: remove tag trigger

docs/oauth-server.md
Previous URL just goes to a "URL not found" page: https://console.developers.google.com/permissions/serviceaccounts?project=_
=> Updating Service Accounts URL to the current one

src/Service.php
The classes generated in `google/apiclient-services` are setting a local property [$serviceName](https://github.com/googleapis/google-api-php-client-services/blob/main/src/Storage.php#L77) which isn't actually defined anywhere.
=> fix: add missing public var used by subclasses

src/Task/Runner.php
Fixes the PHP 8.1 error "Implicit conversion from float ... to int loses precision". The usleep function expects an integer, not a float.
=> fix: PHP 8.1 compatibility for Task\Runner::backOff

src/Service/Exception.php
After the latest update static analysis tools hinted on this wrongly typed structure.
The returned structure of `Exception::getErrors()` is an array with a map of keys and values.
The change was introduced here https://github.com/googleapis/google-api-php-client/pull/2252
```
[
{
"domain": "global",
"reason": "authError",
"message": "Invalid Credentials",
"locationType": "header",
"location": "Authorization"
}
]
```
=> Update return type of `Exception::getErrors()` to its correct structure

src/Service/Exception.php
Based on the definition it should always be an array, but that's not reflected in `REST::getResponseErrors()`.
=> Fix unexpected null value in Service\Exception::$errors

README.md, examples/batch.php, examples/idtoken.php, examples/large-file-download.php, examples/large-file-upload.php, examples/multi-api.php, examples/simple-file-upload.php, examples/simple-query.php
fixing lint errors due to non closure of PHP tags
Fixes: https://github.com/googleapis/google-api-php-client/issues/2316
I ran `php -S localhost:8080 -t examples/` and the example pages load correctly on browser, without any errors on server.
=> fix (style): lint errors

src/Client.php, tests/Google/ClientTest.php
Update Google authorization URI to match `authorization_endpoint` value provided in the [accounts.google.com OIDC Discovery doc](https://accounts.google.com/.well-known/openid-configuration).
=> Update accounts.google.com authorization URI

src/AuthHandler/Guzzle6AuthHandler.php, tests/Google/ClientTest.php
Hi there :wave: 
Here is the patch following this issue https://github.com/googleapis/google-api-php-client/issues/2345
=> feat: make auth http client config extends from default client config

src/Model.php
In the `keyType()` function in `Model.php` we were calling `class_exists()` to find out if a class existed. However, in some cases the value that we were checking could be null. Since PHP 8.1 a deprecation warning is thrown. In this PR we check that the value that we are passing is not null before calling `class_exists()`, thus removing the deprecation
Fixes #2372
=> fix: ensure class_exists is not called with null

README.md, src/Client.php, tests/Google/ClientTest.php
cc @sai-sunder-s @TimurSadykov
b/253077796
=> feat: user-supplied query params for auth url

composer.json
Upgrade minimum Phpseclib version to `3.0.19` in order to patch security vulnerability GHSA-hm7p-r324-hhf3
=> fix: upgrade min phpseclib version

composer.json, phpcs.xml.dist, tests/Google/ClientTest.php
Fixes the tests for refactoring that happened in `google/auth:v1.33.0`.
See https://github.com/googleapis/google-auth-library-php/pull/492
=> chore: fix tests for google/auth v1.33

src/Http/REST.php
Hi, 
In this PR, I replaced `get_class` with `self:class` due to new deprecations in PHP 8.3, which you can read about it [here](https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#:~:text=has%20been%20closed.-,get_class()%20and%20get_parent_class(),-get_class()%20currently)
Since PHP 8.3 is still an RC version, Many things, like upgrading composer packages, need to be done to be compatible with PHP 8.3, but this is a code issue and can be solved right now.
=> fix: php 8.3 deprecated get_class method call without argument

composer.json
Upgrades phpseclib to the patched version 3.0.34
https://github.com/advisories/GHSA-jpr7-q523-hx25
=> fix: phpseclib security vulnerability

src/Client.php
prerequisite for #2563 so that we can properly document parameters
=> chore: fix client phpdoc

composer.json
Issue fixed in 3.0.36.
https://github.com/advisories/GHSA-hg35-mp25-qf6h
=> fix: updates phpseclib because of a security issue

composer.json, src/Client.php, src/Http/Batch.php, src/Service.php, src/Service/Resource.php, tests/Google/ClientTest.php, tests/Google/Service/ResourceTest.php, tests/Google/ServiceTest.php
See also https://github.com/googleapis/google-api-php-client-services/pull/4675
The following manual test worked using this branch:
```php
$universeDomain = 'MY_UNIVERSE_DOMAIN';
$projectId = 'MY_PROJECT_ID';
$client = new Google\Client([
'universe_domain' => $universeDomain,
'scopes' => ['https://www.googleapis.com/auth/cloud-platform'],
]);
$client->useApplicationDefaultCredentials();
$storage = new Google\Service\Storage($client);
$buckets = $storage->buckets->listBuckets($projectId);
foreach ($buckets as $bucket) {
echo $bucket->name . PHP_EOL;
}
```
=> feat: add universe domain support

src/Service/Resource.php, tests/Google/Service/ResourceTest.php
Add the protected `apiVersion` property to the `Resource` class to support the new api version header.
=> feat: Add the protected apiVersion property

src/Client.php, tests/Google/ClientTest.php
This streamlines configuration on par with all other configuration options.
Added unit-tests.
=> Add logger to Client constructor too

src/AccessToken/Revoke.php, src/AccessToken/Verify.php, src/AuthHandler/Guzzle6AuthHandler.php, src/Client.php, src/Http/REST.php, src/Service/Exception.php, src/Task/Composer.php
=> fix: Implicitly marking parameter  as nullable is deprecated

.github/sync-repo-settings.yaml, .github/workflows/tests.yml, src/AccessToken/Revoke.php, src/AccessToken/Verify.php, src/AuthHandler/Guzzle6AuthHandler.php, src/Client.php, src/Http/REST.php, src/Service/Exception.php, src/Task/Composer.php, tests/Google/ClientTest.php
fixes https://github.com/googleapis/google-api-php-client/issues/2640
Adds PHP 8.4 compatibility to the latest PHP 7.4 release (`2.16.0`). This will be tagged as `v2.16.1`
=> fix: add php 8.4 compatibility to latest 7.4 release

src/AccessToken/Verify.php
For #2641 
This pull request includes changes to the `Verify` class in the `src/AccessToken/Verify.php` file to improve type safety by updating the type hints for the `jwt` property and constructor parameter.
Type safety improvements:
* [`src/AccessToken/Verify.php`](diffhunk://#diff-dbcd1e59f54ffa0425222f56eca976fc29e17bc33c82c559e29703ad397a1d41L63-R63): Changed the type hint of the `jwt` property from `\Firebase\JWT\JWT` to `JWT`.
* [`src/AccessToken/Verify.php`](diffhunk://#diff-dbcd1e59f54ffa0425222f56eca976fc29e17bc33c82c559e29703ad397a1d41L72-R72): Updated the type hint of the `jwt` parameter in the constructor from `?string` to `?JWT`.
=> Add correct type for $jwt, should be JWT

src/Task/Composer.php
Finder returns a live iterator that updates as files and directories are removed, causing some items to be skipped during deletion. This change converts the iterator to an array using `iterator_to_array()`, fixing the issue where not all files were deleted in one pass.
Closes https://github.com/googleapis/google-api-php-client-services/issues/6502
=> fix: convert Finder lazy iterator to array before deletion
